### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yanrising** [DeGatchi/mev-template-rs#1]
After command: cargo run
I have error:
Calling allPairsLength from 0x152e…1be3
   ~ [FAIL] Total pairs: AbiError(DecodingError(InvalidName("please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist")))

Node - i use QuickNode

**Comment by degatchi** [comment]
That address is for the fantom network - make sure you're using that specific RPC

**Comment by yanrising** [comment]
Thanks!
