### ISSUE TITLE
Next problem

### ISSUE THREAD

**Issue by yanrising** [DeGatchi/mev-template-rs#2]
All work but after use command "cargo run --release" the following happens:
...
   Compiling ethabi v17.2.0
   Compiling ethers-core v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-contract-abigen v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-providers v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-signers v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-etherscan v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-addressbook v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-solc v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-contract-derive v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-contract v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers-middleware v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling ethers v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)
   Compiling mev-template v0.1.0 (/home/test/projects/mev-template-rs)
    Finished release [optimized] target(s) in 8m 30s
     Running `target/release/mev-template`
Calling allPairsLength from 0x152e…1be3
   ~ [PASS] Total pairs: 23461
test@-virtual-machine:~/projects/mev-template-rs$ 

As far as I understand there should be monitoring - but there is not. 
I apologize for the stupid question - thanks to your programs I started to learn Rust and still do not fully understand the logic of the program.
Do I need to specify any other parameters besides those specified in the env file?

**Comment by degatchi** [comment]
you need a websocket (ws) to run the mempool streaming - is there an error message?

**Comment by yanrising** [comment]
ws in env file -
PRIVATE_KEY=privatekey
NETWORK_RPC=https://greatest-fittest-panorama.discover.quiknode.pro/0000000000000000000000/
NETWORK_WSS=wss://greatest-fittest-panorama.discover.quiknode.pro/0000000000000000000000/
DISCORD_WEBHOOK=https://discordapp.com/api/webhooks/000000000000000000/000000000000000000000000000000000000

No error messages at all. It builds and runs successfully. Then just a message appears:
Calling allPairsLength from 0x152e...1be3
~ [PASS] Total pairs: 23461
and the program finishes. That is, as far as I understand - it collects information about pairs and that's all, further monitoring does not happen

**Comment by degatchi** [comment]
You need to bring in the updates from the repo into your current repo

**Comment by yanrising** [comment]
Thanks
